name: Build Standalone GUI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt6 opencv-python
      - name: Build exe
        run: pyinstaller --onefile --windowed osl_visualizer/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSL-GUI-Windows
          path: dist/main.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt6 opencv-python
      - name: Build app
        run: pyinstaller --onefile --windowed osl_visualizer/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSL-GUI-macOS
          path: dist/main

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0
          pip install pyinstaller pyqt6 opencv-python
      - name: Build binary
        run: pyinstaller --onefile --windowed osl_visualizer/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSL-GUI-Linux
          path: dist/main

